### ISSUE TITLE
latoya - password val

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/component-extravaganza#11]
not feeling too good about this. need to keep practicing
https://github.com/LWatsonlm/component-extravaganza-ga
Cannot figure out why I keep getting this error: http://screencast.com/t/FnO9Aedjby

EDIT: Had the time to review this morning, fixed stupid bugs (closing tags for form /> and missing curly brackets)

**Comment by jshawl** [comment]
ok goooood - gettin those reps in!
