### ISSUE TITLE
Will Hawkins - StopWatch and Validator

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/component-extravaganza#39]
https://github.com/hawkins-will/react-stopwatch

https://github.com/hawkins-will/react-password-validator

Comfort: 4/5

Complete: 5/5

Instead of working on the bonuses, I did two to solidify the basics.

I initially felt like I had no idea what I was doing, but that improved A LOT over the course of this lab.

**Comment by nayana487** [comment]
👍
