### ISSUE TITLE
Nat Carter | component-extravaganza

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/component-extravaganza#41]
[Password Validator](https://github.com/ngcarter/react-password-validator)

Comfort: 2.9 / 5
Completeness: 5 / 5

Right now, the only thing I hate more than this is `this`.

**Comment by amaseda** [comment]
Hope you're feeling a little better about React right now. Happy to talk through any parts of it that you don't understand / absolutely hate.
