### ISSUE TITLE
Ben Shapiro - Stopwatch

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-exercises/component-extravaganza#53]
https://github.com/pretorben/react-stopwatch

Completeness: 5
Comfort Level: 3.5

Going in I thought this would be easier than it was.  I couldn't put together my initial idea of a counter and while loops (or if those are even used in React).  I ended up leaning on the solution, but once I looked through it a bit, I picked it up quickly.

**Comment by superbuggy** [comment]
👍
