### ISSUE TITLE
Habtamu Abere ~ CR5 ~ password validator

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/component-extravaganza#56]
https://github.com/HabRonan/react-password-validator

**Comment by amaseda** [comment]
:+1: let me know if you have any questions about this assignment!

**Comment by HabRonan** [comment]
Yes, I do have a couple of questions about the email forms
1. How do we make sure a user inputs @ and .com after an email
2. Using Password Regex, how do we make sure a password has minimum 6 or 8 characters,one capital, on small and symbol...just the regular strong email combinations.

**Comment by amaseda** [comment]
1. Haven't tried this myself but look into HTML form email validation: http://stackoverflow.com/a/19605847. You could also include some logic in your backend that would search through the incoming string to make sure it contains `@` and ends with a valid URL suffix.

2. Ha, regex can be tricky and unfortunately I'm too well-versed in it. I think this would be a good place to start your research though: https://www.thepolyglotdeveloper.com/2015/05/use-regex-to-test-password-strength-in-javascript/

**Comment by HabRonan** [comment]
Thanks man!
