### ISSUE TITLE
Purdum - Password Validator

### ISSUE THREAD

**Issue by wjpurdum** [ga-wdi-exercises/component-extravaganza#70]
https://github.com/wjpurdum/react-password-validator
Completion 5/5
Comfort 4/5 - this helped a lot!

**Comment by wjpurdum** [comment]
Adding stopwatch: 
https://github.com/wjpurdum/react-stopwatch

**Comment by juancgarcia** [comment]
👍 Glad to hear this lab helped to solidify some ideas.
